### PR TITLE
Language support

### PR DESCRIPTION
**Pull request by amitait**
Anyone can add his language and change the text for its own needs :)

New global vars at the beginning of the document and new 'MotionCAPTCHA_language' function at the bottom.

### CODE REVIEW

**Comment by wjcrowcroft** [comment]
Hey, Thanks for the pull request but I don't think it's necessary - no need to add global vars and translation is easy via the plugin options, as below.

All text strings used in the plugin are passed in as options, and only the defaults are in English. Here's an example of using the plugin in German:

```
$('#mc-form').motionCaptcha({
    // On error:
    errorMsg: 'Bitte versuchen Sie erneut.',

    // On success:
    successMsg: 'Captcha bestanden!',

    // Label displayed above the canvas
    // This could be any HTML string (eg. '<label>Draw this shit yo:</label>'):
    // NB: This is not used yet, planned for 0.2 or will be removed
    label: '<p>Bitte kopieren Sie die Zeichnung, um das Formular abzuschicken:</p>',

    // This message is displayed if the user's browser doesn't support canvas:
    // NB. Not used yet, planned for v0.2 or will be removed
    noCanvasMsg: "Ihr Browser HTML5 Canvas leider nicht unterstützt - bitte versuchen Sie Chrome, Firefox oder Safari.",
});
```

**Comment by amitait** [comment]
Hey,

What if a user has multiple language UI? How can he change it in "one click"
without sending the texts all over again?

**Comment by wjcrowcroft** [comment]
I see what you're saying, yeah. Definitely something that will need some consideration for a future release and thanks for bringing it up.

My suggestion for users with multi-language UIs - given that the plugin must be initialised, and that they are probably already using some form of translation library - would be to pass in the user's preferred language at init. So, an example using `gettext` in PHP would be (off the top of my head):

```
$('#mc-form').motionCaptcha({
    // On error:
    errorMsg: '<?php echo _( "Please try again." ); ?>',

    // On success:
    successMsg: '<?php echo _( "CAPTCHA Passed!." ); ?>',
```

etc. - that would output the correct string in the user's preferred language, if it's in the locale/translation file.

I'll definitely be adding a method to change options for version 0.2, so for RIAs and sites that rely on JavaScript for translation (which may require a single-click translation), they could do something like this:

```
$('#mc-form').motionCaptcha('option', {
    errorMsg: 'plz try again kthx' // etc.
});
```

That would be able to dynamically update the language for a given MotionCAPTCHA instance, after the plugin has been set up.

I think it's an issue that would need a bit more careful consideration to make sure it's as optimised as possible

**Comment by amitait** [comment]
Cool!

The PHP method is great (for now).
Keep up the great work :)

**Pull request closed without merging**
